### ISSUE TITLE
how can play against other bot?

### ISSUE THREAD

**Issue by sijiaxu** [davechurchill/ualbertabot#10]
I try play with other bot under the multiplayer mode, but some time the bot behave very strange, like the unit->morph return true in code, but in fact the unit required resource do not meet, so the morph order fail in game...
but when I play single, the bot works fine...

**Comment by davechurchill** [comment]
Sorry you will have to be more specific with your error, I have no idea how to approach debugging this

**Comment by sijiaxu** [comment]
actually it's my bot's error. but it mainly based on your bot..
the detail error is as below:
I use zerg race. when I play in the single player mode, it all works fine.
so I move to play against with other bot. but the bot behave very strange under multi-player mode.

for example:
1.when my supply is 7/9, i morph a drone, then Broodwar->self()->supplyUsed() return 18 which should be 16..
2.in production manager, when I produce a unit, the canmake and unit->morph return true in code, but in the game the unit's resource is not meet, so the building order fail in game, it is really weird. these function all works fine under single player mode. i really can not figure out the reason.

my bwapi version is 3.7.4 

Thanks

**Comment by davechurchill** [comment]
I don't think I can help if you are using the 3.7.4 version of ualbertabot as we no longer maintain it.

Are you using the version of ualbertabot from this github account? It is using BWAPI version > 4

I am sorry that you are having problems with the older version but a lot of fixes have been made since then and I really don't have the time to help debug problems with deprecated versions of the bot. If you can confirm that you are using an old version then I'll close this ticket.

**Comment by sijiaxu** [comment]
yes, I use an old stable version, it seems necessary to upgrade to 4.0..

2015-07-06 17:45 GMT+08:00 David Churchill notifications@github.com:

**Comment by davechurchill** [comment]
Okay, let me know if you have any problems with the new version, good luck!
