### ISSUE TITLE
Game freezes at start

### ISSUE THREAD

**Issue by MatanBN** [davechurchill/ualbertabot#36]
Hi,
I tried to install UalbertaBot, I installed bwapi 4.1.2, installed bwta (moved the windows files to c:\Windows directory, added environment variables, compiled with visual studio 2013 professional (compilation was successful), opened chaos launcher as admin, gave the the right destination in the configuration file and started the game with UalbertaBot as protoss, but the game freezes at the start every time, do you know what's the problem or what I should do?
thank

**Comment by davechurchill** [comment]
If you watch the instructions it tells you that this is bwta analyzing the
map. It takes a while but only runs once per map

On May 10, 2017 9:02 AM, "MatanBenNoach" <notifications@github.com> wrote:

Hi,
I tried to install UalbertaBot, I installed bwapi 4.1.2, installed bwta
(moved the windows files to c:\Windows directory, added environment
variables, compiled with visual studio 2013 professional (compilation was
successful), opened chaos launcher as admin, gave the the right destination
in the configuration file and started the game with UalbertaBot as protoss,
but the game freezes at the start every time, do you know what's the
problem or what I should do?
thank

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davechurchill/ualbertabot/issues/36>, or mute the thread
