### ISSUE TITLE
why the AI get stuck at the start of the game ...

### ISSUE THREAD

**Issue by sijiaxu** [davechurchill/ualbertabot#8]
sorry about the newbie question, I google a lot but still have not get useful help.

I follow the install step in the wiki and everything is ok until I start the game, the starcraft process seems stuck , have no response. but I try the BWAPI example AI module, it works just fine.

I get no idea about how to find the questions, can some one give me some insight?

Thanks..

**Comment by davechurchill** [comment]
If the bot appears to hang at the beginning of the game it's probably
because BWTA is performing its calculations for the first 30 seconds - 1
minute. This will only happen once per map, so if it gets stuck for 2 or
more minutes then something is wrong

On Sun, May 3, 2015 at 4:51 AM, sijia xu notifications@github.com wrote:

> sorry about the newbie question, I google a lot but still have not get
> useful help.
> 
> I follow the install step in the wiki and everything is ok until I start
> the game, the starcraft process seems stuck , have no response. but I try
> the BWAPI example AI module, it works just fine.
> 
> I get no idea about how to find the questions, can some one give me some
> insight?
> 
> Thanks..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davechurchill/ualbertabot/issues/8.

## 

---

Dave Churchill
cdavid@cs.ualberta.ca
dave.churchill@gmail.com

That's the thing about people who say they hate computers. What they really
hate is lousy programmers.

**Comment by sijiaxu** [comment]
Thanks, davechurchill！ it turn out to be the analyzing of the BWTA , I wait for about 1 minute and bot start to running..

**Comment by davechurchill** [comment]
Awesome, glad I could help!

On Sun, May 3, 2015 at 5:36 PM, sijia xu notifications@github.com wrote:

> Thanks, davechurchill！ it turn out to be the analyzing of the BWTA , I
> wait for about 1 minute and bot start to running..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davechurchill/ualbertabot/issues/8#issuecomment-98556406
> .

## 

---

Dave Churchill
cdavid@cs.ualberta.ca
dave.churchill@gmail.com

That's the thing about people who say they hate computers. What they really
hate is lousy programmers.
